services:
  bridge:
    container_name: bridge
    build: ..
    environment:
      PORT: 8081
      CORS_ENABLE: "true"
      HEARTBEAT_INTERVAL: 10
      RPS_LIMIT: 1000
      CONNECTIONS_LIMIT: 200
      TON_ANALYTICS_ENABLED: "true"
      TON_ANALYTICS_URL: "http://analytics-mock:9090/events"
      TON_ANALYTICS_NETWORK_ID: "-239"
      TON_ANALYTICS_BRIDGE_VERSION: "test-1.0.0"
      TON_ANALYTICS_BRIDGE_URL: "http://bridge-instance1:8080"
    ports:
      - "8081:8081"  # bridge
      - "9103:9103"  # pprof and metrics
    networks:
      - bridge_network
    restart: unless-stopped

  integration:
    build:
      context: ..
      dockerfile: docker/Dockerfile.integration
    container_name: bridge-integration
    environment:
      BRIDGE_URL: "http://bridge:8081/bridge"
    depends_on:
      bridge:
        condition: service_started
    networks:
      - bridge_network
    command: ["/bin/bash", "-c", "make test-bridge-sdk"]
    # command: ["/bin/bash", "-c", "tail -f /dev/null"]

  gointegration:
    build:
      context: ..
      dockerfile: docker/Dockerfile.gointegration
    container_name: bridge-gointegration
    environment:
      BRIDGE_URL: "http://bridge:8081/bridge"
    depends_on:
      bridge:
        condition: service_started
    networks:
      - bridge_network
    command: ["/bin/bash", "-c", "make test-gointegration"]
    # command: ["/bin/bash", "-c", "tail -f /dev/null"]


  benchmark:
    build:
      context: ..
      dockerfile: docker/Dockerfile.benchmark
    container_name: benchmark
    working_dir: /scripts
    environment:
      BRIDGE_URL: "http://bridge:8081/bridge"
      RAMP_UP: "1m"
      HOLD: "3m"
      RAMP_DOWN: "1m"
      SSE_VUS: "500"
      SEND_RATE: "10000"
    depends_on:
      bridge:
        condition: service_started
    networks:
      - bridge_network
    volumes:
      - ../benchmark:/scripts:ro
      - ../benchmark/results:/results
    entrypoint: [ "/bin/sh", "-lc" ]
    command:
      - >
        printf '\n\n======  pprof BEFORE  ======\n\n';
        pprof -top -sample_index=alloc_space -unit=GB -nodecount=5 http://bridge:9103/debug/pprof/allocs 2>/dev/null || true;
        pprof -proto http://bridge:9103/debug/pprof/allocs > /tmp/allocs-before.pb.gz 2>/dev/null || true;
        printf '\n\n====== starting BENCH ======\n\n';
        printf 'Running load test for %s with:\n' "$$TEST_DURATION";
        printf '  - SSE Virtual Users: %s\n' "$$SSE_VUS";
        printf '  - Send Rate: %s msg/s\n' "$$SEND_RATE";
        printf '  - Target: %s\n\n' "$$BRIDGE_URL";
        printf '\n\nPlease wait...\n\n';
        /usr/local/bin/k6 run --quiet --summary-export=/results/summary.json /scripts/bridge_test.js;
        printf '\n\n======  pprof AFTER   ======\n\n';
        pprof -top -sample_index=alloc_space -unit=GB -nodecount=5 http://bridge:9103/debug/pprof/allocs 2>/dev/null || true;
        pprof -proto http://bridge:9103/debug/pprof/allocs > /tmp/allocs-after.pb.gz 2>/dev/null || true;
        printf '\n\n======   pprof DIFF   ======\n\n';
        pprof -top -sample_index=alloc_space -unit=GB -nodecount=5 -base=/tmp/allocs-before.pb.gz /tmp/allocs-after.pb.gz || true;
        rm -f /tmp/allocs-before.pb.gz /tmp/allocs-after.pb.gz 2>/dev/null || true;
        printf '\n\n============================\n\n';

networks:
  bridge_network:
    driver: bridge