name: lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  fmtcheck:
    name: go fmt check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '1.24.6'
          cache: false
      - name: go fmt check
        run: make fmtcheck

  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '1.24.6'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          args: --timeout=10m --color=always

  goimports:
    runs-on: ubuntu-latest
    name: goimports check
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: goimports check
        uses: DarthBenro008/goimports-check-action@v0.2.0
        with:
          root-path: './' # The relative root path to run goimports
          excludes: "./yacc/"